# -*- coding: utf-8 -*-
"""natural_language_processing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMfYuQWdveMUJ49kHk3soksPpCyeG16-
"""

pip install youtube-search

from youtube_search import YoutubeSearch          # đọc đường dẫn của bài hát từ bên youtube

import webbrowser
mysong = input('Nhập tên bài hát cần tìm:')
result = YoutubeSearch(mysong,max_results = 10).to_dict()
print(result)
url = 'https://www.youtube.com/'+result[0]['url_suffix']
print(url)
#webbrowser() # do chạy trên colab nên hàng này bị lỗi nếu chạy trên máy thì bình thơngf

from openpyxl import Workbook  # đọc file exel
from youtube_search import YoutubeSearch         # đọc đường dẫn của bài hát từ bên youtube
import webbrowser
mysong = input('Nhập tên bài hát cần tìm:')
result = YoutubeSearch(mysong,max_results = 10).to_dict()
print(result)
url = 'https://www.youtube.com/'+result[0]['url_suffix']
print(url)
data = Workbook()
sheet = data.active
for i in range(10):
  print(result[i]['title'])
  print(result[i],['url_sufix'])
  url = 'https://www.youtube.com/'+result[i]['url_suffix']
  print(url)
  sheet['A'+str(i+1)] = i+1
  sheet['B' + str(i+1)] = result[i]['title']
  sheet['C' + str(i+1)] = result[i]['url_suffix']
  sheet['D' + str(i+1)] = result[i]['views']
  #sheet['E' + str(i+1)] = result[i]['']       # làm thêm các trường khác thồi lượng chiếu và xuất bản năm nào

data.save('Thonhke.xlxs')

pip install SpeechRecognition pydub

file = '/content/male.wav'  # đường dẫn                   # chuyển từ âm thanh sang văn bản
import speech_recognition as sr                                 # ko_KO : hàn quốc
r = sr.Recognizer()                                             #th_TH : thai lan
with sr.AudioFile(file) as source:                              #ja_JA : nhật
  audio_data = r.record(source)                                 #vi_VI : việt nam
  text = r.recognize_google(audio_data,language = 'vi_VI')             #fr_FR: phap
  print(text)

# cắt dữ liệu
import speech_recognition as sr
r = sr.Recognizer()
with sr.AudioFile('/content/male.wav') as source:
  audio1= r.record(source , duration = 4)
  audio2 = r.record(source, offset =10,duration = 10)
print(r.recognize_google(audio1,language='vi_VI'))  # chia ra đoạn dịch tiếng việt
print(r.recognize_google(audio2,language='en_EN'))  # chia ra đoạn dịch tiếng anh

pip install gTTS

# chuyển từ văn bản sang âm thanh
from gtts import gTTS
import os
#A='/content/Transcrip.txt'
A = 'Do you recall, not long ago / We would walk on the sidewalk' # tạo xuống hàng/
speak = gTTS(text = A, lang='uk',slow = False)
speak.save('Transcrip3.mp3')
#playsound('Transcrip.mp3') # dung de phat am thanh khi chạy tren máy tính
#os.remove('Transcrip.mp3') # chỉ dùng được trong may tính dẻ remove

pip install googletrans==3.1.0a0

from googletrans import Translator
translator = Translator()
translation = translator.translate('Chúng tối luôn phát triển AI trong thời gian tới',dest = 'en')
print(translation.text)