# -*- coding: utf-8 -*-
"""XULYAMTHANH.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4xX_8DhSMQBIl7iq8SHG5oL-PGp3-hB
"""

pip install librosa

import librosa
import numpy as np
import matplotlib.pyplot as plt

wav = '/content/3a13_136116_VO TAN THINH_DAY 8.mp3'
audio, sr = librosa.load(wav)  # hàm trả về 2 biến audio
time = np.linspace(0,audio.shape[0]/ sr,num = audio.shape[0])
plt.plot(time, audio, color = "red")
plt.xlabel("Time(s)")
plt.ylabel("Amplitude (quantized)")
plt.title("Wav file visualization")
plt.axhline(y=0, color = 'b', linestyle = '-')
plt.show()

n_data_points = audio.shape[0]
window_size = 40*(10**10-3) # tách thành các cữa sổ có thời lượng 40ms và khoảng cách giữa các cữa sổ là 10
offset = 10*(10**-3)
window_length = int(round(window_size * sr )) # thời lượng của 1 cữa sổ
window_step = int(round(offset*sr)) # khoảng cách giữa các cữa sổ
n_windows = int(np.ceil(float(abs(n_data_points - window_length)/window_step))) # tổng của sổ  nhận được
                                                                                #từ file âm thanh sau khi đã xác định 2 thông số trên
print("window length:",window_length)
print("window_step:",window_step)
print("number of windows:",n_windows  )

pad_data_length = n_windows * window_step  + window_length
#z = np.zeros((pad_data_length - n_data_points))
#pad_data = np.append(audio,z)
#print(audio.shape)
#print(pad_data.shape)

print(n_data_points)
print(pad_data_length)
print(pad_data_length-n_data_points)